package com.eugene.securite_mo_de_passe.view;

import com.eugene.securite_mo_de_passe.MainApp;

import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;

/**
 * The controller for the root layout. The root layout provides the basic
 * application layout containing a menu bar and space where other JavaFX
 * elements can be placed.
 *
 * @author ETOUNDI II Eugene Sebastien Cedric P.
 */
public class SecuriteRootLayoutController {

    // Reference to the main application
    private MainApp mainApp;

    /**
     * Is called by the main application to give a reference back to itself.
     *
     * @param mainApp
     */
    public void setMainApp(MainApp mainApp) {
        this.mainApp = mainApp;
    }

    /**
     * Opens an about dialog.
     */
    @FXML
    private void handleAbout() {
        Alert alert = new Alert(AlertType.INFORMATION);
        alert.setTitle("HASH WORDS CRACKER");
        alert.setHeaderText("About Security Project");
        alert.setContentText("Author : ETOUNDI II Eugene Sebastien Cedric P." +
                            "\nProfessor : M. SAHA Pierre \n" +

                            "\nThis program allow to search a matching in a file" +
                            "\nbetween a hash get by user and one word of " +
                            "\nthe WordList.txt get by him or generated by the program. \n" +

                            "\nProduct Version\n" +
                            "HASH WORDS CRACKER 1.0\n" +
                            "\n" +

                            "Build Information\n" +
                            "Version 1.0\n" +
                            "Date: 2020-03-28\n" +
                            "\n" +

                            "Java\n" +
                            "11.0.1+13-LTS, Oracle Corporation\n" +
                            "\n" +

                            "Operating System\n" +
                            "Windows 10, amd64\n" +
                            "\n" +

                            "Copyright © ETOUNDI II Eugène Sébastien Cédric P.");

        alert.showAndWait();
    }

    /**
     * Closes the application.
     */
    @FXML
    private void handleExit() {
        System.exit(0);
    }
}